/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountVote implements Serializable {

    private static final long serialVersionUID = -49769143;

    private ULong  id;
    private String voteAddress;
    private ULong  voteAccountId;
    private ULong  voteCount;
    private ULong  accountId;

    public AccountVote() {}

    public AccountVote(AccountVote value) {
        this.id = value.id;
        this.voteAddress = value.voteAddress;
        this.voteAccountId = value.voteAccountId;
        this.voteCount = value.voteCount;
        this.accountId = value.accountId;
    }

    public AccountVote(
        ULong  id,
        String voteAddress,
        ULong  voteAccountId,
        ULong  voteCount,
        ULong  accountId
    ) {
        this.id = id;
        this.voteAddress = voteAddress;
        this.voteAccountId = voteAccountId;
        this.voteCount = voteCount;
        this.accountId = accountId;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getVoteAddress() {
        return this.voteAddress;
    }

    public void setVoteAddress(String voteAddress) {
        this.voteAddress = voteAddress;
    }

    public ULong getVoteAccountId() {
        return this.voteAccountId;
    }

    public void setVoteAccountId(ULong voteAccountId) {
        this.voteAccountId = voteAccountId;
    }

    public ULong getVoteCount() {
        return this.voteCount;
    }

    public void setVoteCount(ULong voteCount) {
        this.voteCount = voteCount;
    }

    public ULong getAccountId() {
        return this.accountId;
    }

    public void setAccountId(ULong accountId) {
        this.accountId = accountId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountVote (");

        sb.append(id);
        sb.append(", ").append(voteAddress);
        sb.append(", ").append(voteAccountId);
        sb.append(", ").append(voteCount);
        sb.append(", ").append(accountId);

        sb.append(")");
        return sb.toString();
    }
}
